2025-02-08 11:04:49 - INFO - Start polling
2025-02-08 11:04:49 - INFO - Run polling for bot @odfopjdfiohniodfhopjdfh_bot id=7915533202 - 'ijdsgijsiodgjsiodgjiosg'
2025-02-08 11:04:59 - INFO - Update id=652331065 is handled. Duration 250 ms by bot id=7915533202
2025-02-08 11:05:01 - INFO - Connecting to 149.154.175.53:443/TcpFull...
2025-02-08 11:05:01 - INFO - Connection to 149.154.175.53:443/TcpFull complete!
2025-02-08 11:05:03 - INFO - Starting direct file download in chunks of 131072 at 0, stride 131072
2025-02-08 11:05:03 - INFO - File lives in another DC
2025-02-08 11:05:03 - INFO - Connecting to 149.154.167.41:443/TcpFull...
2025-02-08 11:05:05 - INFO - Connection to 149.154.167.41:443/TcpFull complete!
2025-02-08 11:05:05 - INFO - Exporting auth for new borrowed sender in DcOption(id=2, ip_address='149.154.167.41', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, this_port_only=False, secret=None)
2025-02-08 11:05:11 - INFO - Disconnecting from 149.154.175.53:443/TcpFull...
2025-02-08 11:05:11 - INFO - Disconnection from 149.154.175.53:443/TcpFull complete!
2025-02-08 11:05:11 - INFO - Disconnecting from 149.154.167.41:443/TcpFull...
2025-02-08 11:05:11 - INFO - Disconnection from 149.154.167.41:443/TcpFull complete!
2025-02-08 11:05:15 - INFO - Update id=652331066 is not handled. Duration 14905 ms by bot id=7915533202
2025-02-08 11:05:15 - ERROR - Cause exception while process update id=652331066 by bot id=7915533202
IndexError: list index out of range
Traceback (most recent call last):
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\RUSTYCHKA\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\RUSTYCHKA\Desktop\new_vk_project\handlers\start.py", line 226, in start_callback
    if ratio(post["text"], ids['lenta'][-1]) < 0.5:
                           ~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-02-08 11:05:23 - INFO - Update id=652331067 is handled. Duration 157 ms by bot id=7915533202
2025-02-08 11:05:24 - INFO - Connecting to 149.154.175.53:443/TcpFull...
2025-02-08 11:05:24 - INFO - Connection to 149.154.175.53:443/TcpFull complete!
2025-02-08 11:05:25 - INFO - Starting direct file download in chunks of 131072 at 0, stride 131072
2025-02-08 11:05:25 - INFO - File lives in another DC
2025-02-08 11:05:25 - INFO - Connecting to 149.154.167.41:443/TcpFull...
2025-02-08 11:05:27 - INFO - Connection to 149.154.167.41:443/TcpFull complete!
2025-02-08 11:05:27 - INFO - Exporting auth for new borrowed sender in DcOption(id=2, ip_address='149.154.167.41', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=False, this_port_only=False, secret=None)
2025-02-08 11:05:33 - INFO - Disconnecting from 149.154.175.53:443/TcpFull...
2025-02-08 11:05:33 - INFO - Disconnection from 149.154.175.53:443/TcpFull complete!
2025-02-08 11:05:33 - INFO - Disconnecting from 149.154.167.41:443/TcpFull...
2025-02-08 11:05:33 - INFO - Disconnection from 149.154.167.41:443/TcpFull complete!
